#!configuration/base.yaml

application:
  port: 8000
  host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "ridhimakhyalappa"
  password: "ridhima@7557"
  database_name: "ridhimakhyalappa"
email_client:
  base_url: "localhost"
  sender_email: "ridhima_khyalappa@heartcore.co.jp"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000